import Ember from 'ember';

var users = [{id: 1, url: "/assets/images/tomsters/0-rfc.png", title: "RFC Tomster", desc: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI."},
			  {id: 2, url: "/assets/images/tomsters/1-canary.png", title: "Canary Release Tomster", desc: "Efficiently unleash cross-media information without cross-media value. Quickly maximize timely deliverables for real-time schemas. Dramatically maintain clicks-and-mortar solutions without functional solutions."},
			  {id: 3, url: "/assets/images/tomsters/3-release.png", title: "Release Tomster", desc:"Completely synergize resource taxing relationships via premier niche markets. Professionally cultivate one-to-one customer service with robust ideas. Dynamically innovate resource-leveling customer service for state of the art customer service."},
			  {id: 4, url: "/assets/images/tomsters/5k.png", title: "5k Tomster", desc: "Phosfluorescently engage worldwide methodologies with web-enabled technology. Interactively coordinate proactive e-commerce via process-centric \"outside the box\" thinking. Completely pursue scalable customer service through sustainable potentialities."},
			  {id: 5, url: "/assets/images/tomsters/atlanta.png", title: "Atlanta Tomster", desc: "Collaboratively administrate turnkey channels whereas virtual e-tailers. Objectively seize scalable metrics whereas proactive e-services. Seamlessly empower fully researched growth strategies and interoperable internal or \"organic\" sources."},
			  {id: 6, url: "/assets/images/tomsters/austin.png", title: "Austin Tomster", desc: "Credibly innovate granular internal or \"organic\" sources whereas high standards in web-readiness. Energistically scale future-proof core competencies vis-a-vis impactful experiences. Dramatically synthesize integrated schemas with optimal networks."},
			  {id: 7, url: "/assets/images/tomsters/boston.png", title: "Boston Tomster", desc: "As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing this has to change a man."},
			  {id: 8, url: "/assets/images/tomsters/builtwith.png", title: "Built-With Tomster", desc: "Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a historical process which mankind is carrying out in accordance with the natural laws of human development."},
			  {id: 9, url: "/assets/images/tomsters/dallas.png", title: "Dallas Tomster", desc: "Buy why, some say, the moon? Why choose this as our goal? And they may as well ask why climb the highest mountain?"},
			  {id: 10, url: "/assets/images/tomsters/denver.png", title: "Denver Tomster", desc: "There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning."},
			  {id: 11, url: "/assets/images/tomsters/houston.png", title: "Houston Tomster", desc: "The path of a cosmonaut is not an easy, triumphant march to glory. You have to get to know the meaning not just of joy but also of grief, before being allowed in the spacecraft cabin.Across the sea of space, the stars are other suns."},
			  {id: 12, url: "/assets/images/tomsters/jacksonville.png", title: "Jacksonville Tomster", desc: "Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission: to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man has gone before."},
			  {id: 13, url: "/assets/images/tomsters/kayaking.png", title: "Kayaking Tomster", desc: "We want to explore. We’re curious people. Look back over history, people have put their lives at stake to go out and explore … We believe in what we’re doing. Now it’s time to go. Curious that we spend more time congratulating people who have succeeded than encouraging people who have not."},
			  {id: 14, url: "/assets/images/tomsters/london.png", title: "London Tomster", desc: "We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone, and one which we intend to win."},
			  {id: 15, url: "/assets/images/tomsters/louisville.png", title: "Louisville Tomster", desc:"Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science."},
			  {id: 16, url: "/assets/images/tomsters/montevideo.png", title: "Montevideo Tomster", desc: "Bavaria ipsum dolor sit amet mei glacht, Biagadn! Obandln nimmds vo de a ganze? I moan oiwei schoo wo hi Gschicht Schuabladdla, Meidromml iabaroi glei i mechad dee Schwoanshaxn hogg ma uns zamm. Hod Schmankal naa o’ha hob i an Suri, kloan fensdaln. Heimatland Servas schüds nei Schmankal iabaroi singd gor. Ramasuri mi Baamwach pfenningguat spernzaln naa kimmt vo de, Brotzeit. Dringma aweng hod moand Blosmusi mechad da, hog di hi is, zünftig."},
			  {id: 17, url: "/assets/images/tomsters/munich.png", title: "Munich Tomster", desc: "Sepp noch da Giasinga Heiwog Maßkruag wos Biakriagal sog i des wiad a Mordsgaudi auf der Oim, da gibt’s koa Sünd pfiad de wuid."},
			  {id: 18, url: "/assets/images/tomsters/philly.png", title: "Philly Tomster", desc: "Um Godds wujn Greichats Charivari wia da Buachbinda Wanninger Edlweiss Semmlkneedl Obazda do vui huift vui allerweil wos: Schaung kost nix Milli pfenningguat hallelujah sog i, luja Weiznglasl zua i hab an a do legst di nieda in da greana Au."},
			  {id: 19, url: "/assets/images/tomsters/pirate.png", title: "Pirate Tomster", desc: "Cat o'nine tails Sink me run a shot across the bow knave deadlights pinnace bilge water hearties Jolly Roger come about. Careen rigging bilge water long clothes hardtack Jack Tar bowsprit no prey, no pay square-rigged cackle fruit. Handsomely crack Jennys tea cup spirits reef marooned lad gabion lee stern loot."},
			  {id: 20, url: "/assets/images/tomsters/seattle.png", title: "Seattle Tomster", desc: "Cat o'nine tails Sink me run a shot across the bow knave deadlights pinnace bilge water hearties Jolly Roger come about. Careen rigging bilge water long clothes hardtack Jack Tar bowsprit no prey, no pay square-rigged cackle fruit. Handsomely crack Jennys tea cup spirits reef marooned lad gabion lee stern loot."},
			  {id: 21, url: "/assets/images/tomsters/sherpa.png", title: "Sherpa Tomster", desc: "Smartly execution dock Chain Shot brigantine rigging pressgang mutiny Sink me loaded to the gunwalls walk the plank. Interloper draught gangplank bilge shrouds brigantine scuttle mizzenmast topmast cutlass. Reef scallywag dance the hempen jig Pirate Round furl topgallant come about topsail rigging square-rigged."},
			  {id: 22, url: "/assets/images/tomsters/slc.png", title: "Salt Lake City Tomster", desc: "Fenningguat heid gfoids ma sagrisch guad Lewakaas fei oba Buam. Sowos i resch Semmlkneedl Auffisteign, gelbe Rüam fei Edlweiss Auffisteign heid i bin a woschechta Bayer. Gscheckate es wea ko, dea ko Breihaus moand oa abfieseln, Maibam. "},
			  {id: 23, url: "/assets/images/tomsters/teaching.png", title: "Teaching Tomster", desc:"Af blärrd sog i Schneid gar nia need eana, nia need am acht’n Tag schuf Gott des Bia fias. Nia need Gamsbart bittschön Broadwurschtbudn nix gwihss spernzaln obandln i hob di liab! Sauba Gschicht hod nia liberalitas Bavariae, Biagadn."}];
export default Ember.Component.extend({
	users: users,
	usersDetail: false,
	actions: {
		toggleUserDetail() {
			this.set('usersDetail', !this.get('usersDetail'));
		}
	}
});	